src/Entity/Recipes.php
<?php

namespace App\Entity;

use App\Entity\Users;
use App\Entity\Favoris;
use App\Entity\Category;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\RecipesRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[UniqueEntity(fields: ['Title'], message: 'Il existe déjà une recette nommée avec ce titre.')]
#[ORM\Entity(repositoryClass: RecipesRepository::class)]
#[Vich\Uploadable]

class Recipes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Title;

    #[Vich\UploadableField(mapping: 'recipe_images', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string', nullable:true)]
    private ?string $imageName = null;
    
    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $description;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $updatedAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\Column(type: 'string', length: 255)]
    private $ingredient_1;

    #[ORM\Column(type: 'string', length: 255)]
    private $ingredient_2;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ingredient_3;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ingredient_5;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ingredient_4;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ingredient_6;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ingredient_7;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ingredient_8;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ingredient_9;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ingredient_10;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ingredient_11;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ingredient_12;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ingredient_13;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ingredient_14;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ingredient_15;

    #[ORM\Column(type: 'string', length: 255)]
    private $preparation_1;

    #[ORM\Column(type: 'string', length: 255)]
    private $preparation_2;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $preparation_3;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $preparation_4;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $preparation_5;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $preparation_6;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'recipes')]
    #[ORM\JoinColumn(nullable: false)]
    private $Category;

    #[ORM\ManyToOne(targetEntity: category::class, inversedBy: 'categorie')]
    #[ORM\JoinColumn(nullable: false)]
    private $category;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $basket= FALSE;

    #[ORM\ManyToOne(targetEntity: Users::class, inversedBy: 'recipe')]
    #[ORM\JoinColumn(nullable: false)]
    private $users;

    #[ORM\OneToMany(mappedBy: 'recipe', targetEntity: Favoris::class)]
    private $favoris;


    public function __construct()
    {
        $this->favoris = new ArrayCollection();
    }

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
          
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }
    
    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIngredients(): ?string
    {
        return $this->ingredients;
    }

    public function setCreatedAd(\DateTimeInterface $createdAd): self
    {
        $this->createdAd = $createdAd;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getIngredient1(): ?string
    {
        return $this->ingredient_1;
    }

    public function setIngredient1(string $ingredient_1): self
    {
        $this->ingredient_1 = $ingredient_1;

        return $this;
    }

    public function getIngredient2(): ?string
    {
        return $this->ingredient_2;
    }

    public function setIngredient2(string $ingredient_2): self
    {
        $this->ingredient_2 = $ingredient_2;

        return $this;
    }

    public function getIngredient3(): ?string
    {
        return $this->ingredient_3;
    }

    public function setIngredient3(?string $ingredient_3): self
    {
        $this->ingredient_3 = $ingredient_3;

        return $this;
    }

    public function getIngredient5(): ?string
    {
        return $this->ingredient_5;
    }

    public function setIngredient5(?string $ingredient_5): self
    {
        $this->ingredient_5 = $ingredient_5;

        return $this;
    }

    public function getIngredient4(): ?string
    {
        return $this->ingredient_4;
    }

    public function setIngredient4(?string $ingredient_4): self
    {
        $this->ingredient_4 = $ingredient_4;

        return $this;
    }

    public function getIngredient6(): ?string
    {
        return $this->ingredient_6;
    }

    public function setIngredient6(?string $ingredient_6): self
    {
        $this->ingredient_6 = $ingredient_6;

        return $this;
    }

    public function getIngredient7(): ?string
    {
        return $this->ingredient_7;
    }

    public function setIngredient7(?string $ingredient_7): self
    {
        $this->ingredient_7 = $ingredient_7;

        return $this;
    }

    public function getIngredient8(): ?string
    {
        return $this->ingredient_8;
    }

    public function setIngredient8(?string $ingredient_8): self
    {
        $this->ingredient_8 = $ingredient_8;

        return $this;
    }

    public function getIngredient9(): ?string
    {
        return $this->ingredient_9;
    }

    public function setIngredient9(?string $ingredient_9): self
    {
        $this->ingredient_9 = $ingredient_9;

        return $this;
    }

    public function getIngredient10(): ?string
    {
        return $this->ingredient_10;
    }

    public function setIngredient10(?string $ingredient_10): self
    {
        $this->ingredient_10 = $ingredient_10;

        return $this;
    }

    public function getIngredient11(): ?string
    {
        return $this->ingredient_11;
    }

    public function setIngredient11(?string $ingredient_11): self
    {
        $this->ingredient_11 = $ingredient_11;

        return $this;
    }

    public function getIngredient12(): ?string
    {
        return $this->ingredient_12;
    }

    public function setIngredient12(?string $ingredient_12): self
    {
        $this->ingredient_12 = $ingredient_12;

        return $this;
    }

    public function getIngredient13(): ?string
    {
        return $this->ingredient_13;
    }

    public function setIngredient13(?string $ingredient_13): self
    {
        $this->ingredient_13 = $ingredient_13;

        return $this;
    }

    public function getIngredient14(): ?string
    {
        return $this->ingredient_14;
    }

    public function setIngredient14(?string $ingredient_14): self
    {
        $this->ingredient_14 = $ingredient_14;

        return $this;
    }

    public function getIngredient15(): ?string
    {
        return $this->ingredient_15;
    }

    public function setIngredient15(?string $ingredient_15): self
    {
        $this->ingredient_15 = $ingredient_15;

        return $this;
    }

    public function getPreparation1(): ?string
    {
        return $this->preparation_1;
    }

    public function setPreparation1(string $preparation_1): self
    {
        $this->preparation_1 = $preparation_1;

        return $this;
    }

    public function getPreparation2(): ?string
    {
        return $this->preparation_2;
    }

    public function setPreparation2(string $preparation_2): self
    {
        $this->preparation_2 = $preparation_2;

        return $this;
    }

    public function getPreparation3(): ?string
    {
        return $this->preparation_3;
    }

    public function setPreparation3(?string $preparation_3): self
    {
        $this->preparation_3 = $preparation_3;

        return $this;
    }

    public function getPreparation4(): ?string
    {

templates/pages/front/contact.html.twig
{% extends '/bases/baseFo.html.twig' %}

{% block title %} Contactez-moi | Evlow Foodies{% endblock %} 
{% block body %}

{% for message in app.flashes('contact') %}
<div class="alert-contact">
    {{ message }}
</div>
{% endfor %}

<article class="article-contact">
    <section class="section-contact">
        <p class="p-contact">Vous avez une question ?</p>
        <p class="p-contact">Des suggestions à faire ?</p>
        <h3 class="home-h3 ">
            <span>Contactez-moi !</span>
        </h3>
    </section>

        <section class="content-contact">
        <div class="form-contact">
            <div class="bloc-name-contact">
          
            <div class="bloc-contact">
               
                {{ form_start(formContact) }}
                {{ form_label(formContact.firstName) }}
                {{ form_widget(formContact.firstName) }}
            </div>
            <div class="bloc-contact">
                {{ form_label(formContact.lastName) }}
                {{ form_widget(formContact.lastName) }}
            </div>
        </div>
            <div class="bloc-email">
                {{ form_label(formContact.email) }}
                {{ form_widget(formContact.email) }}
            </div>
    
            <div class="bloc-message">
                {{ form_label(formContact.message) }}
                {{ form_widget(formContact.message) }}
            </div>
            <div class="bloc-input">
                {{ form_label(formContact.envoyer) }}
                {{ form_widget(formContact.envoyer) }}
                {{ form_end(formContact) }}
            </div>
            <span class="span-contact">*Champs obligatoires</span>
        </div>
   </section>
</article>
{% endblock %}

templates/pages/front/home.html.twig
{% extends '/bases/baseFo.html.twig' %}
{% block title %}Evlow Foodies {% endblock %} 
{% block body %}
<!--INTRODUCTION-->
<div class="content-intro">
    <div class="paragraphe">
        <p>En manque d’inspiration ? Vous retrouverez-ici des idées de recettes.</p>
        
        <div>
            {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
            <p>Envie de partager vos recettes ? Inscrivez-vous et à vous de concocter !</p>
            <a class="btn-login-home" href="{{path('app_fo_registration')}}">S'inscrire</a>
            {% else %}
        
            {% endif %}
        </div>
    </div>
</div>


<!--FOOD ?-->
<article class="home-article">
    <section class="home-section">
        <h3 class="home-h3"><span>Qu’est ce qu’on mange ?</span></h3>
        <p class="p-home">Qu'est ce qu'on mange ? Cette question est posée une multitude de fois ! Il est parfois diffcile de trouver
            une idée de repas ! Avec Evlow Foodies, vous trouverez des recettes, pour tous les goûts et facile à faire.
        </p>
    </section>
    <!--SHARE RECIPES ?-->
    <section class="home-section">
        <h3 class="home-h3" ><span>Envie de partager vos recettes ?</span></h3>
        <p class="p-home">Vous souhaitez partager vos succulentes recettes et en faire profiter à un maximum de personnes ? Cela est
            possible ! il suffit de t'inscrire, de te connecter, de te laisser guider et le tour est joué ! Rien de plus
            facile, crois-moi </p>
    </section>
    <!--LAST RECIPES ?-->
    <section class="home-section">
        <h3 class="home-h3"><span>Les dernières recettes !</span></h3>
        <p class="p-recipe">Vous retrouverez-ici les dernièrs recettes mises en ligne !</p>
        <div class="carts">
            <div class="content-card">
                {% for recipe in recipes %}
                <div class="card"> 
                    <h3 class="recipes-h3">{{recipe.title}}</h3>
                    <div class="content-recipe-img">
                    <img class="recipe-img-home" src="{{vich_uploader_asset(recipe, 'imageFile') }}" alt="{{recipe.title}}">
                </div>
                    <a class="btn-recipe" href="{{ path('app_fo_recipe_sheet', { id: recipe.id }) }}">Voir la recette</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</article>
{% endblock %}

templates/pages/front/little_gones_recipes.html.twig
{% extends '/bases/baseFo.html.twig' %}

{% block title %}
Recettes p'tits gônes | Evlow Foodies
{% endblock %}

{% block body %}
<!--INTRODUCTION-->
<div class="content-intro-gones">
    <div class="paragraphe-gones">
        <p>Les recettes P'tits Gônes</p>
    </div>
</div>
<div class="carts">
    <section class="content-card">
        {% for recipe in recipes %}
        <article class="card">
            <img class="recipe-img-home" src="{{vich_uploader_asset(recipe, 'imageFile')}}" alt="{{recipe.title}}">
            <h3 class="recipes-h3">{{recipe.title}}</h3>
            <a class="btn-recipe" href="{{ path('app_fo_recipe_sheet', { id: recipe.id }) }}">Voir la recette</a>
            {% if is_granted("ROLE_USER") %}
            {% set isFavorite = false %}
            {% for favoris in recipe.favoris %}
                {% if favoris.id == app.user.id %}
                    {% set isFavorite = true %}
                {% endif %}    
            {% endfor %}
            {% if isFavorite %}
            <a href="{{ path('add_bo_favorites', {id: recipe.id}) }}"><img class="img-favoris" src="{{asset('assets/picture/black-favoris.svg') }}" alt="icone coeur vide"></a>
            {% else %}
            <a href="{{ path('add_bo_favorites', {id: recipe.id}) }}"><img class="img-favoris" src="{{asset('assets/picture/black-favoris.svg') }}" alt="icone coeur plein"></a>
            {% endif %}

        {% else %}
        <img class="img-favoris" src="{{asset('assets/picture/black-favoris.svg') }}" alt="icone coeur vide"></li>        
        {% endif %}
</article>
{% endfor %}
</section>
</div>
{% endblock %}

templates/pages/front/recipe_sheet.html.twig
{% extends '/bases/baseFo.html.twig' %}

{% block body %}
<div class="content-intro-recipe-sheet">
    <div class="paragraphe-recipe-sheet">
        <h3 class="h3-recipe-sheet">{{recipe.title}}</h3>
    </div>
    <div class="content-img-sheet">
        <img class="recipe-sheet-img" src="{{vich_uploader_asset(recipe, 'imageFile')}}" alt="{{recipe.title}}">   
    </div>
    <p class="recipe-description">{{recipe.description}}</p>
</div>
<article class="content-article">
    <section class="section-ingredients">
        <div class="bloc-title">
            <div class="ovale">
                <h4 class="title-flex"><img class="ingredients" src="{{ asset('assets/picture/ingredient.svg') }}"
                        alt="image ingrédients" />Ingédients
                </h4>
            </div>
        </div>

        <ul>
            <li>♦ {{recipe.ingredient1}}</li>
            <li>♦ {{recipe.ingredient2}}</li>
            <li>{% if recipe.ingredient3 is null %} {% else %}♦ {{recipe.ingredient3}}</li> {% endif %}
            <li>{% if recipe.ingredient4 is null %} {% else %}♦ {{recipe.ingredient4}}</li> {% endif %}       
            <li>{% if recipe.ingredient5 is null %} {% else %}♦ {{recipe.ingredient5}}</li> {% endif %}
            <li>{% if recipe.ingredient6 is null %} {% else %}♦ {{recipe.ingredient6}}</li> {% endif %}    
            <li>{% if recipe.ingredient7 is null %} {% else %}♦ {{recipe.ingredient7}}</li> {% endif %}
            <li>{% if recipe.ingredient8 is null %} {% else %}♦ {{recipe.ingredient8}}</li> {% endif %}       
            <li>{% if recipe.ingredient9 is null %} {% else %}♦ {{recipe.ingredient9}}</li> {% endif %}
            <li>{% if recipe.ingredient10 is null %} {% else %}♦ {{recipe.ingredient10}}</li> {% endif %}    
            <li>{% if recipe.ingredient11 is null %} {% else %}♦ {{recipe.ingredient11}}</li> {% endif %}
            <li>{% if recipe.ingredient12 is null %} {% else %}♦ {{recipe.ingredient12}}</li> {% endif %}    
            <li>{% if recipe.ingredient13 is null %} {% else %}♦ {{recipe.ingredient13}}</li> {% endif %}
            <li>{% if recipe.ingredient14 is null %} {% else %}♦ {{recipe.ingredient14}}</li> {% endif %}       
            <li>{% if recipe.ingredient15 is null %} {% else %}♦ {{recipe.ingredient15}}</li> {% endif %}
        </ul>

    </section>

    <section class="section-preparations">

        <div class="bloc-title">
            <div class="ovale">
                <h4 class="title-flex"><img class="preparations" src="{{ asset('assets/picture/preparation.svg') }}"
                        alt="image préparation" />Préparations
                </h4>
            </div>
        </div>
        
        <ul>
            <li>{% if recipe.preparation1 is null %} {% else %}<span class="list-number">1.</span> {{recipe.preparation1}}</li> {% endif %}
            <li>{% if recipe.preparation2 is null %} {% else %}<span class="list-number">2.</span> {{recipe.preparation2}}</li> {% endif %}
            <li>{% if recipe.preparation3 is null %} {% else %}<span class="list-number">3.</span> {{recipe.preparation3}}</li> {% endif %}
            <li>{% if recipe.preparation4 is null %} {% else %}<span class="list-number">4.</span> {{recipe.preparation4}}</li> {% endif %}
            <li>{% if recipe.preparation5 is null %} {% else %}<span class="list-number">5.</span> {{recipe.preparation5}}</li> {% endif %}
            <li>{% if recipe.preparation6 is null %} {% else %}<span class="list-number">6.</span> {{recipe.preparation6}}</li> {% endif %}

        </ul>
    </section>
</article>



{% endblock %}

templates/pages/front/savory_recipes.html.twig
{% extends '/bases/baseFo.html.twig' %}

{% block title %}
Recettes salées | Evlow Foodies  
{% endblock %}

{% block body %}
 <!--INTRODUCTION-->
 <div class="content-intro-savory">
     <div class="paragraphe-savory">
         <p>Les recettes salées</p>
     </div>
 </div>
 <div class="carts">
        <section class="content-card">
            {% for recipe in recipes %}
            <article class="card"> 
                <img class="recipe-img-home" src="{{vich_uploader_asset(recipe, 'imageFile')}}" alt="{{recipe.title}}">
                <h3 class="recipes-h3">{{recipe.title}}</h3>
                <a class="btn-recipe" href="{{ path('app_fo_recipe_sheet', { id: recipe.id }) }}">Voir la recette</a>
                
                {% if is_granted("ROLE_USER") %}
                {% set isFavorite = false %}
                {% for favoris in recipe.favoris %}
                    {% if favoris.id == app.user.id %}
                        {% set isFavorite = true %}
                    {% endif %}    
                {% endfor %}
                {% if isFavorite %}
                <a href="{{ path('add_bo_favorites', {id: recipe.id}) }}"><img class="img-favoris" src="{{asset('assets/picture/red-favoris.svg') }}" alt="icone favoris"></a>
                {% else %}
                <a href="{{ path('add_bo_favorites', {id: recipe.id}) }}"><img class="img-favoris" src="{{asset('assets/picture/black-favoris.svg') }}" alt="icone favoris"></a>
                {% endif %}
    
            {% else %}
            <img class="img-favoris" src="{{asset('assets/picture/black-favoris.svg') }}" alt="icone favoris"></li>        
            {% endif %}
    </article>
    {% endfor %}
    </section>
    </div>
    {% endblock %}

templates/pages/front/specific_recipes.html.twig
{% extends '/bases/baseFo.html.twig' %}

{% block title %}
Régimes spécifiques | Evlow Foodies |
{% endblock %}

{% block body %}
 <!--INTRODUCTION-->
 <div class="content-intro-specific">
     <div class="paragraphe-specific">
         <p>Les régimes spécifiques</p>
     </div>
 </div>
 <div class="carts">
    <section class="content-card">
        {% for recipe in recipes %}
        <article class="card"> 
            <img class="recipe-img-home" src="{{vich_uploader_asset(recipe, 'imageFile')}}" alt="{{recipe.title}}">
            <h3 class="recipes-h3">{{recipe.title}}</h3>
            {% if is_granted("ROLE_USER") %}
            {% set isFavorite = false %}
            {% for favoris in recipe.favoris %}
            {% if favoris.id == app.user.id %}
            {% set isFavorite = true %}
            {% endif %}
            {% endfor %}
            {% if isFavorite %}
            <a href="{{ path('remove_bo_favorites', {id: recipe.id}) }}"><img class="img-favoris"
                    src="{{asset('assets/picture/red-favoris.svg') }}" alt="icone favoris"></a>
            {% else %}
            <a href="{{ path('add_bo_favorites', {id: recipe.id}) }}"><img class="img-favoris"
                    src="{{asset('assets/picture/black-favoris.svg') }}" alt="icone favoris"></a>
            {% endif %}

            {% else %}
            <img class="img-favoris" src="{{asset('assets/picture/black-favoris.svg') }}" alt="icone favoris"></li>
            {% endif %}
        </article>
        {% endfor %}
    </section>   
</div>
{% endblock %}

templates/pages/front/sweet_recipes.html.twig
{% extends '/bases/baseFo.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" />
{% endblock %}

{% block title %}
Recettes sucrées | Evlow Foodies
{% endblock %}


{% block body %}
<!--INTRODUCTION-->
<div class="content-intro-sweet">
    <div class="paragraphe-sweet">
        <p>Les recettes sucrées</p>
    </div>
</div>
<div class="carts">
    <section class="content-card">
        {% for recipe in recipes %}
        <article class="card">
            <img class="recipe-img-home" src="{{vich_uploader_asset(recipe, 'imageFile')}}" alt="{{recipe.title}}">
            <h3 class="recipes-h3">{{recipe.title}}</h3>
            <a class="btn-recipe" href="{{ path('app_fo_recipe_sheet', { id: recipe.id }) }}">Voir la recette</a>
            {% if is_granted("ROLE_USER") %}
            {% set isFavorite = false %}
            {% for favoris in recipe.favoris %}
            {% if favoris.id == app.user.id %}
            {% set isFavorite = true %}
            {% endif %}
            {% endfor %}
            {% if isFavorite %}
            <a href="{{ path('remove_bo_favorites', {id: recipe.id}) }}"><img class="img-favoris"
                    src="{{asset('assets/picture/red-favoris.svg') }}" alt="icone favoris"></a>
            {% else %}
            <a href="{{ path('add_bo_favorites', {id: recipe.id}) }}"><img class="img-favoris"
                    src="{{asset('assets/picture/black-favoris.svg') }}" alt="icone favoris"></a>
            {% endif %}

            {% else %}
            <img class="img-favoris" src="{{asset('assets/picture/black-favoris.svg') }}" alt="icone favoris"></li>
            {% endif %}
        </article>
        {% endfor %}
    </section>
</div>
{% endblock %}